import Head from "next/head"
import React from "react"
import Link from "next/link"

interface LayoutPropsTypes {
  title: string
  children: React.ReactNode
}

const Layout = ({ title, children }: LayoutPropsTypes) => {
  return (
    <>
      <Head>
        <title>{title ? title : "header"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen flex-col justify-between ">
        <header>
          <nav>
            <Link href="/">
              <a className="text-lg font-bold">weshop</a>
            </Link>
          </nav>
        </header>
        <main className="sm:p-3 md:p-5">{children}</main>
        <footer>footer</footer>
      </div>
    </>
  )
}

export default Layout
